package com.maestrx.studentcontrol.teacherapp.utils

object Constants {
    const val LESSON_DATA = "LESSON_DATA"
    const val NEW_LESSON_DATE = "NEW_LESSON_DATE"
    const val GROUP_ID = "GROUP_ID"
    const val LESSON_UPDATED = "LESSON_UPDATED"

    const val TIME_CHECK_DELAY = 2_000L
    const val TIME_RECESS = 15

    const val MESSAGE_ERROR_SAVING_LESSON = "MESSAGE_ERROR_SAVING_LESSON"
    const val MESSAGE_ERROR_DELETING_LESSON = "MESSAGE_ERROR_DELETING_LESSON"
    const val MESSAGE_ERROR_SAVING_GROUP = "MESSAGE_ERROR_SAVING_GROUP"
    const val MESSAGE_ERROR_DELETING_GROUP = "MESSAGE_ERROR_DELETING_GROUP"
    const val MESSAGE_ERROR_SAVING_STUDENT = "MESSAGE_ERROR_SAVING_STUDENT"
    const val MESSAGE_ERROR_DELETING_STUDENT = "MESSAGE_ERROR_DELETING_STUDENT"
    const val MESSAGE_ERROR_SAVING_SUBJECT = "MESSAGE_ERROR_SAVING_SUBJECT"
    const val MESSAGE_ERROR_DELETING_SUBJECT = "MESSAGE_ERROR_DELETING_SUBJECT"
}