package com.maestrx.studentcontrol.teacherapp.utils

object Constants {
    const val DEBUG_TAG = "TeacherAppDBG"

    const val LESSON_DATA = "LESSON_DATA"
    const val NEW_LESSON_DATE = "NEW_LESSON_DATE"
    const val GROUP_ID = "GROUP_ID"
    const val LESSON_UPDATED = "LESSON_UPDATED"

    const val EXCEL_FORMAT = ".xlsx"
    const val EXCEL_N_COLUMN_SIZE = 1200
    const val EXCEL_NAME_COLUMN_SIZE = 9000

    const val TIMEOUT = 2_000
    const val TIME_CHECK_DELAY = 1_000L
    const val TIME_RECESS = 15

    const val MESSAGE_ERROR_SAVING_LESSON = "MESSAGE_ERROR_SAVING_LESSON"
    const val MESSAGE_ERROR_DELETING_LESSON = "MESSAGE_ERROR_DELETING_LESSON"
    const val MESSAGE_ERROR_SAVING_GROUP = "MESSAGE_ERROR_SAVING_GROUP"
    const val MESSAGE_ERROR_DELETING_GROUP = "MESSAGE_ERROR_DELETING_GROUP"
    const val MESSAGE_ERROR_SAVING_STUDENT = "MESSAGE_ERROR_SAVING_STUDENT"
    const val MESSAGE_ERROR_DELETING_STUDENT = "MESSAGE_ERROR_DELETING_STUDENT"
    const val MESSAGE_ERROR_SAVING_SUBJECT = "MESSAGE_ERROR_SAVING_SUBJECT"
    const val MESSAGE_ERROR_DELETING_SUBJECT = "MESSAGE_ERROR_DELETING_SUBJECT"
    const val MESSAGE_ERROR_DELETING_ALL_DATA = "MESSAGE_ERROR_DELETING_ALL_DATA"
    const val MESSAGE_ERROR_EXPORT = "MESSAGE_ERROR_EXPORT"
    const val MESSAGE_ERROR_SAVING_MARKS = "MESSAGE_ERROR_SAVING_MARKS"
    const val MESSAGE_ERROR_IMPORT = "MESSAGE_ERROR_IMPORT"

    const val MESSAGE_OK_DELETING_ALL_DATA = "MESSAGE_OK_DELETING_ALL_DATA"
    const val MESSAGE_OK_IMPORT = "MESSAGE_OK_IMPORT"
    const val MESSAGE_OK_EXPORT = "MESSAGE_END_EXPORT"

    const val MESSAGE_SHOW_MARK_DIALOG = "MESSAGE_SHOW_MARK_DIALOG"
}